version: '3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
  web:
    image: wordpress
    build: .
    volumes:
      - ./themes/:/var/www/html/wp-content/themes/semantic-ui-wordpress
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
